xen/link: add llvm coverage sections to linker script
This patch adds macros for LLVM coverage related sections to the generic
linker script header and apply them to x86 linker script (the only
platform I've tested).

Without the linker script, both GNU ld and LLVM ld.lld would warn:

  (GNU ld)

  ld    -melf_x86_64 --no-warn-rwx-segments -T arch/x86/xen.lds prelink.o --build-id=sha1 \
      --orphan-handling=warn ./.xen-syms.1.o -o xen-syms
  ld: warning: orphan section `__llvm_prf_names' from `prelink.o' being placed in section `__llvm_prf_names'
  ld: warning: orphan section `__llvm_prf_cnts[__profc___bitmap_empty]' from `prelink.o' being placed in section `__llvm_prf_cnts'
  ...
  ld: warning: orphan section `__llvm_covfun[__covrec_A4C6B5AC625FBB6D]' from `prelink.o' being placed in section `__llvm_covfun'
  ld: warning: orphan section `.rela__llvm_prf_data' from `prelink.o' being placed in section `.rela.dyn'

  (LLVM ld.lld)

  /lib/llvm-20/bin/ld.lld    -melf_x86_64  -T arch/x86/xen.lds prelink.o --build-id=sha1 \
      --orphan-handling=warn ./.xen-syms.1.o -o xen-syms
  ld.lld: warning: prelink.o:(__llvm_covfun) is being placed in '__llvm_covfun'
  ...
  ld.lld: warning: prelink.o:(__llvm_prf_cnts) is being placed in '__llvm_prf_cnts'
  ld.lld: warning: prelink.o:(__llvm_prf_data) is being placed in '__llvm_prf_data'

Besides the warnings, GNU ld places those sections mostly fine but LLVM
ld.lld places __llvm_prf_names among the init sections, and causes trouble
when we attempt to parse the dumped coverage data.

  $ /lib/llvm-20/bin/llvm-readelf -WS xen/xen-syms

    There are 29 section headers, starting at offset 0x315c948:

    Section Headers:
      [Nr] Name              Type            Address          Off    Size   ES Flg Lk Inf Al
      [ 0]                   NULL            0000000000000000 000000 000000 00      0   0  0
      [ 1] .text             PROGBITS        ffff82d040200000 008000 2a7a93 00  AX  0   0 4096
      [ 2] .rodata           PROGBITS        ffff82d0404a8000 2b0000 06b570 00  WA  0   0 16
      [ 3] .note.gnu.build-id NOTE           ffff82d040513570 31b570 000024 00   A  0   0  4
      [ 4] __llvm_prf_names  NOTE            ffff82d040513594 31b594 122153 00  AR  0   0  1
      [ 5] .init.text        PROGBITS        ffff82d040636000 43e000 072a65 00  AX  0   0 16
      [ 6] .init.data        PROGBITS        ffff82d0406b0000 4b8000 05d108 00  WA  0   0 32768
      [ 7] .data.read_mostly PROGBITS        ffff82d04070e000 516000 018ef0 00  WA  0   0 128
      [ 8] .data             PROGBITS        ffff82d040727000 52f000 00d744 00  WA  0   0 4096
      [ 9] __llvm_prf_cnts   PROGBITS        ffff82d040734748 53c748 0b3050 00  WA  0   0  8
      [10] __llvm_prf_data   PROGBITS        ffff82d0407e7798 5ef798 0dfc40 00  WA  0   0  8
      [11] .bss              NOBITS          ffff82d0408c8000 6cf3d8 120830 00  WA  0   0 4096
      [12] .debug_abbrev     PROGBITS        0000000000000000 6cf3d8 077982 00      0   0  1
      [13] .debug_info       PROGBITS        0000000000000000 746d5a 9b3fdd 00      0   0  1
      [14] .debug_str        PROGBITS        0000000000000000 10fad37 04815b 01  MS  0   0  1
      [15] .debug_str_offsets PROGBITS       0000000000000000 1142e92 228264 00      0   0  1
      [16] .debug_line       PROGBITS        0000000000000000 136b0f6 26e481 00      0   0  1
      [17] .debug_line_str   PROGBITS        0000000000000000 15d9577 00329f 01  MS  0   0  1
      [18] .debug_frame      PROGBITS        0000000000000000 15dc818 03d290 00      0   0  8
      [19] .debug_loclists   PROGBITS        0000000000000000 1619aa8 1ca7a0 00      0   0  1
      [20] .debug_rnglists   PROGBITS        0000000000000000 17e4248 0670a9 00      0   0  1
      [21] .debug_addr       PROGBITS        0000000000000000 184b2f1 0a5f28 00      0   0  1
      [22] .debug_aranges    PROGBITS        0000000000000000 18f1219 000480 00      0   0  1
      [23] __llvm_covfun     PROGBITS        0000000000000000 18f16a0 d5e485 00   R  0   0  8
      [24] __llvm_covmap     PROGBITS        0000000000000000 264fb28 0308c0 00   R  0   0  8
      [25] .comment          PROGBITS        0000000000000000 26803e8 000056 01  MS  0   0  1
      [26] .symtab           SYMTAB          0000000000000000 2680440 695448 18     27 117614  8
      [27] .strtab           STRTAB          0000000000000000 2d15888 446f67 00      0   0  1
      [28] .shstrtab         STRTAB          0000000000000000 315c7ef 000155 00      0   0  1

  $ sudo xencov read | tee >/dev/null problem.profraw
  $ /lib/llvm-20/bin/llvm-profdata merge problem.profraw -o problem.profdata

    warning: problem.profraw: malformed instrumentation profile data: symbol name is empty
    error: no profile can be merged

This linker script fixes both the warnings and placement issues.

Signed-off-by: Wentao Zhang <zhangwt1997@gmail.com>